### ISSUE TITLE
Display Open Source Components in Application itself

### ISSUE THREAD

**Issue by d89** [h-da/geli#105]
As far as I know, it is not enough to mention the used open source components in the readme alone. Instead, they need to be available to the end user from the web frontend of the application itself.

**Suggestion:** Place them in a modal within the application, when the user clicks a small link in the header / footer with he title "Licenses & Open Source".

### Todos
- [x] Add a site to geli which contains all used Licenses
- [x] Genereate a JSON with all used packages by nlf
- [x] Parse the JSON to fill the site with conttent
- [x] Remove license part of readme

**Comment by aeimer** [comment]
#126 does a bugix for the docker container. Afterwards it should work fine
