### ISSUE TITLE
tracking translations

### ISSUE THREAD

**Issue by mleppla** [h-da/geli#754]
The following issues containing translations will be tracked:
- [x] #560 tooltips
- [x] #549 german translations
- [x]  #753 rework german translations
- [x] #858 Automatic missing translation detection via sentry.
- [x] #836 Missing `'resetPassword.requestReset'` fix.
